[project]
name = "squawktuah"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "paho-mqtt>=2.1.0",
    "piper-tts>=1.3.0",
    "rpi-gpio>=0.7.1",
]
